#!/bin/bash
echo "Adding."
git add .
echo "Enter commit message:"
read MSG
echo "Commiting..."
git commit -m $MSG

echo "Pulling....."
git pull lab
echo "Pushing......."
if [ $1 = 'd' ]
then
	git push -u lab daily
elif [$1 = 'm' ]
then
	git push -u lab master
else
	echo "ENTER VALID COMMAND B!"
fi
echo "DONE"
